apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
  name: grafana
  namespace: grafana
spec:
  tls:
  - hosts:
    - web.thewindgod.com
    secretName: windstatsweb-tls
  rules:
  - host: web.thewindgod.com
    http:
      paths:
      - backend:
          serviceName: windstatsweb
          servicePort: 8080
        path: /

