apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: windstatsweb
  name: windstatsweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windstatsweb
  template:
    metadata:
      labels:
        app: windstatsweb
    spec:
      containers:
      - image: registry:5000/windstats-web:latest
        name: windstatsweb
        ports:
        - containerPort: 80
        readinessProbe:
            httpGet:
              path: /
              port: 80
        livenessProbe:
            httpGet:
              path: /
              port: 80
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 32Mi
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: windstatsweb
spec:
  selector:
    app: windstatsweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: windstatsweb
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: windstatsweb
  targetCPUUtilizationPercentage: 80
