apiVersion: v1
kind: ConfigMap
metadata:
  name: windstatsd
data:
  config.yaml: |-
    dbaddr: http://influxdb:8086
    dbuser: windstats
    dbname: windstats
    dbpass: windstats
    apiaddr: http://88.97.23.70:81
    refresh: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: windstatsd
  name: windstatsd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windstatsd
  template:
    metadata:
      labels:
        app: windstatsd
    spec:
      containers:
      - image: github.com/costap/windstats/cmd/windstatsd
        name: windstatsd
        ports:
        - containerPort: 8080
        env:
        - name: WINDSTATS_CONFIG_PATH
          value: /etc/windstads
        volumeMounts:
        - name: config
          mountPath: /etc/windstads
          readOnly: true
        readinessProbe:
            httpGet:
              path: /
              port: 8080
        livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 32Mi
            cpu: 20m
      volumes:
       - name: config
         configMap:
           name: windstatsd
